### ISSUE TITLE
Input Data

### ISSUE THREAD

**Issue by xue1liu2** [MaidouPP/gc_net_stereo#1]
what is your Input Data?
Do you write the program by one paper which is End-to-End Learning of Geometry and Context for Deep Stereo Regression?

Can you give more presentation?

Thank you anyway.

**Comment by MaidouPP** [comment]
Sorry about late response. My input data to the network is the whole image, which could be gray or RGB. I generate a image list file which states each image's location and during training I randomly choose one image to feed it into the network. 

And yes, that's the paper I refer to.

**Comment by MaidouPP** [comment]
Hi. I just updated code and it's pretty clear how to feed data.
