### ISSUE TITLE
数据和步骤

### ISSUE THREAD

**Issue by QZ1219** [MaidouPP/gc_net_stereo#2]
你好，请问 你的训练数据集是在哪获取的，另可以把过程写的更清楚一些吗？
谢谢

**Comment by MaidouPP** [comment]
数据可以使用Scene Flow数据集和KITTI的stereo数据集，代码中用到的是Scene Flow，它的groundtruth是pfm格式。在run之前，为你的数据集生成一个.lst文件，每一行存放某张训练图片的文件位置，具体读入方式可以从代码中看出。
