### ISSUE TITLE
网络收敛不了

### ISSUE THREAD

**Issue by guandog** [MaidouPP/gc_net_stereo#3]
网络基本收敛不了

**Comment by MaidouPP** [comment]
网络收敛确实比较差，可能需要继续调整参数，但是目前我的做法和论文基本一致。这个项目很早之前已经停止，只是放到github上来存一下。

**Comment by guandog** [comment]
我的做法也和论文基本一致。但也收敛不了。不知论文作者不公开源代码是不是隐藏了什么trick。你的这个项目怎么停止啦？是有更好性能的算法吗？
